=== 2047244/webstack_lab/website/XML_LAB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<psp:schema xmlns:psp="http://www.w3.org/2001/XMLSchema">
<psp:element name="APPSTORE">
<psp:complexType>
<psp:sequence>
<psp:element name="AppDetails" maxOccurs="10" >
<psp:complexType>
<psp:sequence>
<psp:element name="APPID" type="psp:integer"></psp:element>
<psp:element name="APPNAME" type="psp:string"></psp:element>
<psp:element name="DEVELOPER" type="psp:string"></psp:element>
<psp:element name="RELEASEDATE" type="psp:string"></psp:element>
<psp:element name="VERSION" type="psp:string"></psp:element>
<psp:element name="DOWNLOADS" type="NOOFDOWNLOADS"></psp:element>
</psp:sequence>
</psp:complexType>
</psp:element>
</psp:sequence>
</psp:complexType>
</psp:element>
<psp:simpleType name="NOOFDOWNLOADS">
<psp:restriction base="psp:integer">
<psp:maxExclusive value="5000"></psp:maxExclusive>
<psp:minExclusive value="1"></psp:minExclusive>
</psp:restriction>
</psp:simpleType>
</psp:schema>

=== 2047244/webstack_lab/website/XML_LAB.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XML_LAB.xsl"?>
<APPSTORE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XML_LAB.xsd">
  <AppDetails>
    <APPID>001</APPID>
    <APPNAME>WhatsAPP</APPNAME>
    <DEVELOPER>WhatsAPP Inc.</DEVELOPER>
    <RELEASEDATE>MAY2015</RELEASEDATE>
    <VERSION>V1.0</VERSION>
    <DOWNLOADS>500</DOWNLOADS>
  </AppDetails>
  <AppDetails>
    <APPID>002</APPID>
    <APPNAME>Facebook</APPNAME>
    <DEVELOPER>Facebook Inc.</DEVELOPER>
    <RELEASEDATE>AUG2001</RELEASEDATE>
    <VERSION>V6.0</VERSION>
    <DOWNLOADS>900</DOWNLOADS>
  </AppDetails>
  <AppDetails>
    <APPID>003</APPID>
    <APPNAME>SnapChat</APPNAME>
    <DEVELOPER>SnapChat Inc.</DEVELOPER>
    <RELEASEDATE>FEB2014</RELEASEDATE>
    <VERSION>V1.6</VERSION>
    <DOWNLOADS>579</DOWNLOADS>
  </AppDetails>
  <AppDetails>
    <APPID>004</APPID>
    <APPNAME>PUBG</APPNAME>
    <DEVELOPER>Tencent Inc.</DEVELOPER>
    <RELEASEDATE>DEC2018</RELEASEDATE>
    <VERSION>V5.0</VERSION>
    <DOWNLOADS>1523</DOWNLOADS>
  </AppDetails>
  <AppDetails>
    <APPID>005</APPID>
    <APPNAME>Chrome</APPNAME>
    <DEVELOPER>Google Inc.</DEVELOPER>
    <RELEASEDATE>MAR2000</RELEASEDATE>
    <VERSION>V9.5</VERSION>
    <DOWNLOADS>995</DOWNLOADS>
  </AppDetails>
</APPSTORE>
